name: Build and Deploy to GKE

on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: powerful-bounty-469218-q0
  GAR_LOCATION: us-central1
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: webapp-deployment
  IMAGE_NAME: 3-tier-todo-app

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    # Permissions are no longer needed for SA Key authentication
    # but it's safe to leave them.

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    # --- THIS STEP IS UPDATED ---
    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}' # Use the service account key secret

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      run: |-
        docker build \
          --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/my-app-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
          --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/my-app-repo/${{ env.IMAGE_NAME }}:latest" \
          .

    - name: Push Docker image to Artifact Registry
      run: |-
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/my-app-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/my-app-repo/${{ env.IMAGE_NAME }}:latest"

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    # --- THIS STEP IS UPDATED ---
    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}' # Use the service account key secret

    - name: Get GKE cluster credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # --- THIS IS THE UPDATED DEPLOYMENT LOGIC ---
    - name: Substitute image tag in Kubernetes manifest
      run: |-
        sed -i "s|IMAGE_PLACEHOLDER|${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/my-app-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" kubernetes-manifests/webapp.yaml

    - name: Deploy to GKE using apply
      run: |-
        kubectl apply -f kubernetes-manifests/mongo.yaml
        kubectl apply -f kubernetes-manifests/webapp.yaml

    - name: Wait for rollout to finish
      run: kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=300s
